server:
  port: 8085
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: TaskModule
        uri: http://localhost:8081/
        predicates:
        - Path=/tasks/**
      - id: UserModule
        uri: http://localhost:8083/
        predicates:
        - Path=/users/**
      - id: NotificationModule
        uri: http://localhost:8084/
        predicates:
          - Path=/notifications/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  registerWithEureka:
       - true
  fetchRegistry:
       - true